name: weather_warehouse
version: '1.0'
config-version: 2

profile: weather_warehouse

model-paths: ["models"]
test-paths: ["tests"]

models:
  weather_warehouse:
    staging:
      +materialized: view
    marts:
      +materialized: table
