weather_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: de
      password: de
      port: 5432
      dbname: warehouse
      schema: analytics
      threads: 2
