cities:
  - name: Hyderabad
    latitude: 17.3850
    longitude: 78.4867
  - name: Mumbai
    latitude: 19.0760
    longitude: 72.8777
  - name: Delhi
    latitude: 28.6139
    longitude: 77.2090
  - name: Bengaluru
    latitude: 12.9716
    longitude: 77.5946
  - name: Chennai
    latitude: 13.0827
    longitude: 80.2707
